"""
Team abbreviation dictionaries for sports league data processing.

This module provides mappings between team names and their standard abbreviations
for use in formatting, statistics, and visualization tools.

Contents:
    - team_abbr_EPL: dict mapping full English Premier League team names to 3-letter abbreviations.
    - team_abbr_FIFA: dict mapping FIFA 3-letter codes to country names.
"""

team_abbr_EPL = {"Arsenal": "ARS",
                 "Aston Villa": "AVL",
                 "Barnsley": "BAR",
                 "Birmingham City": "BIR",
                 "Blackburn Rovers": "BLA",
                 "Blackpool": "BLK",
                 "Bolton Wanderers": "BOL",
                 "Bournemouth": "BOU",
                 "Bradford City": "BRD",
                 "Brentford": "BRE",
                 "Brighton & Hove Albion": "BRI",
                 "Bristol City": "BRIS",
                 "Burnley": "BUR",
                 "Cardiff City": "CAR",
                 "Charlton Athletic": "CHA",
                 "Chelsea": "CHE",
                 "Coventry City": "COV",
                 "Crystal Palace": "CRY",
                 "Derby County": "DER",
                 "Everton": "EVE",
                 "Fulham": "FUL",
                 "Huddersfield Town": "HUD",
                 "Hull City": "HUL",
                 "Ipswich Town": "IPS",
                 "Leeds United": "LEE",
                 "Leicester City": "LEI",
                 "Liverpool": "LIV",
                 "Luton Town": "LUT",
                 "Manchester City": "MCI",
                 "Middlesbrough": "MID",
                 "Millwall": "MIL",
                 "Manchester United": "MUN",
                 "Newcastle United": "NEW",
                 "Norwich City": "NOR",
                 "Nottingham Forest": "NOT",
                 "Oldham Athletic": "OLD",
                 "Plymouth Argyle": "PLY",
                 "Preston North End": "PNE",
                 "Portsmouth": "POR",
                 "Queens Park Rangers": "QPR",
                 "Reading": "REA",
                 "Rotherham": "ROT",
                 "Sheffield United": "SHU",
                 "Sheffield Wednesday": "SHW",
                 "Southampton": "SOU",
                 "Stoke City": "STK",
                 "Sunderland": "SUN",
                 "Swansea City": "SWA",
                 "Swindon Town": "SWI",
                 "Tottenham Hotspur": "TOT",
                 "Tottenham": "TOT",
                 "Watford": "WAT",
                 "West Bromwich Albion": "WBA",
                 "West Ham United": "WHU",
                 "West Ham": "WHU",
                 "Wigan Athletic": "WIG",
                 "Wimbledon": "WIM",
                #  "Wolverhampton": "WOL",
                 "Wolverhampton Wanderers": "WOL"}

team_abbr_FIFA = {
    'AFG': 'Afghanistan',
    'ALB': 'Albania',
    'ALG': 'Algeria',
    'ASA': 'American Samoa',
    'AND': 'Andorra',
    'ANG': 'Angola',
    'AIA': 'Anguilla',
    'ATG': 'Antigua and Barbuda',
    'ARG': 'Argentina',
    'ARM': 'Armenia',
    'ARU': 'Aruba',
    'AUS': 'Australia',
    'AUT': 'Austria',
    'AZE': 'Azerbaijan',
    'BAH': 'Bahamas',
    'BHR': 'Bahrain',
    'BAN': 'Bangladesh',
    'BRB': 'Barbados',
    'BLR': 'Belarus',
    'BEL': 'Belgium',
    'BLZ': 'Belize',
    'BEN': 'Benin',
    'BER': 'Bermuda',
    'BHU': 'Bhutan',
    'BOL': 'Bolivia',
    'BIH': 'Bosnia-Herzegovina',
    'BOT': 'Botswana',
    'BOS': 'Bosnia and Herzegovina',
    'BON': 'Bonaire',
    'BRA': 'Brazil',
    'VGB': 'British Virgin Islands',
    'BRU': 'Brunei',
    'BUL': 'Bulgaria',
    'BFA': 'Burkina Faso',
    'BDI': 'Burundi',
    'CAM': 'Cambodia',
    'CMR': 'Cameroon',
    'CAN': 'Canada',
    'CAP': 'Cape Verde',
    'CPV': 'Cabo Verde',
    'CAY': 'Cayman Islands',
    'CTA': 'Central African Republic',
    'CHA': 'Chad',
    'CHI': 'Chile',
    'CHN': 'China PR',
    'TPE': 'Taiwan',
    'COL': 'Colombia',
    'COM': 'Comoros',
    'CGO': 'Congo',
    'COD': 'Congo DR',
    'COK': 'Cook Islands',
    'CRC': 'Costa Rica',
    'CIV': "Cote d'Ivoire",
    'CRO': 'Croatia',
    'CUB': 'Cuba',
    'CUW': 'Curacao',
    'CYP': 'Cyprus',
    'CZE': 'Czechia',
    'DEN': 'Denmark',
    'DJI': 'Djibouti',
    'DMA': 'Dominica',
    'DOM': 'Dominican Republic',
    'ECU': 'Ecuador',
    'EGY': 'Egypt',
    'SLV': 'El Salvador',
    'ENG': 'England',
    'EQG': 'Equatorial Guinea',
    'ERI': 'Eritrea',
    'EST': 'Estonia',
    'SWZ': 'Eswatini',
    'ETH': 'Ethiopia',
    'FRO': 'Faroe Islands',
    'FIJ': 'Fiji',
    'FIN': 'Finland',
    'FRA': 'France',
    'FRE': 'French Guiana',
    'GAB': 'Gabon',
    'GAM': 'Gambia',
    'GEO': 'Georgia',
    'GER': 'Germany',
    'GHA': 'Ghana',
    'GIB': 'Gibraltar',
    'GRE': 'Greece',
    'GRN': 'Grenada',
    'GUM': 'Guam',
    'GUA': 'Guatemala',
    'GUI': 'Guinea',
    'GNB': 'Guinea-Bissau',
    'GUY': 'Guyana',
    'HAI': 'Haiti',
    'HON': 'Honduras',
    'HKG': 'Hong Kong',
    'HUN': 'Hungary',
    'ISL': 'Iceland',
    'IND': 'India',
    'IDN': 'Indonesia',
    'IRN': 'Iran',
    'IRQ': 'Iraq',
    'ISR': 'Israel',
    'ITA': 'Italy',
    'IVO': 'Ivory Coast',
    'JAM': 'Jamaica',
    'JPN': 'Japan',
    'JOR': 'Jordan',
    'KAZ': 'Kazakhstan',
    'KEN': 'Kenya',
    'PRK': 'North Korea',
    'KOR': 'South Korea',
    'KOS': 'Kosovo',
    'KUW': 'Kuwait',
    'KGZ': 'Kyrgyzstan',
    'LAO': 'Laos',
    'LVA': 'Latvia',
    'LIB': 'Lebanon',
    'LES': 'Lesotho',
    'LBR': 'Liberia',
    'LBY': 'Libya',
    'LIE': 'Liechtenstein',
    'LTU': 'Lithuania',
    'LUX': 'Luxembourg',
    'MAC': 'Macau',
    'MAD': 'Madagascar',
    'MWI': 'Malawi',
    'MAS': 'Malaysia',
    'MDV': 'Maldives',
    'MLI': 'Mali',
    'MLT': 'Malta',
    'MTN': 'Mauritania',
    'MRI': 'Mauritius',
    'MEX': 'Mexico',
    'MDA': 'Moldova',
    'MNG': 'Mongolia',
    'MNE': 'Montenegro',
    'MSR': 'Montserrat',
    'MAR': 'Morocco',
    'MOZ': 'Mozambique',
    'MYA': 'Myanmar',
    'NAM': 'Namibia',
    'NEP': 'Nepal',
    'NED': 'Netherlands',
    'NCL': 'New Caledonia',
    'NZL': 'New Zealand',
    'NCA': 'Nicaragua',
    'NIG': 'Niger',
    'NGA': 'Nigeria',
    'MKD': 'North Macedonia',
    'NIR': 'Northern Ireland',
    'NOR': 'Norway',
    'OMA': 'Oman',
    'PAK': 'Pakistan',
    'PLE': 'Palestine',
    'PAN': 'Panama',
    'PNG': 'Papua New Guinea',
    'PAR': 'Paraguay',
    'PER': 'Peru',
    'PHI': 'Philippines',
    'POL': 'Poland',
    'POR': 'Portugal',
    'PUR': 'Puerto Rico',
    'QAT': 'Qatar',
    'IRL': 'Republic of Ireland',
    'ROU': 'Romania',
    'RUS': 'Russia',
    'RWA': 'Rwanda',
    'SAM': 'Samoa',
    'SMR': 'San Marino',
    'STP': 'Sao Tomé e Príncipe',
    'KSA': 'Saudi Arabia',
    'SAI': 'Saarland',
    'SCO': 'Scotland',
    'SEN': 'Senegal',
    'SRB': 'Serbia',
    'SEY': 'Seychelles',
    'SLE': 'Sierra Leone',
    'SIN': 'Singapore',
    'ST': 'Sao Tome and Principe',
    'SAO': 'Sao Tome and Principe',
    'SVK': 'Slovakia',
    'SVN': 'Slovenia',
    'SOL': 'Solomon Islands',
    'SOM': 'Somalia',
    'SWA': 'Swaziland',
    'RSA': 'South Africa',
    'SSD': 'South Sudan',
    'ESP': 'Spain',
    'SRI': 'Sri Lanka',
    'SKN': 'St. Kitts and Nevis',
    'LCA': 'St. Lucia',
    'VIN': 'St. Vincent and the Grenadines',
    'SDN': 'Sudan',
    'SUR': 'Suriname',
    'SWE': 'Sweden',
    'SUI': 'Switzerland',
    'SYR': 'Syria',
    'TAH': 'Tahiti',
    'TJK': 'Tajikistan',
    'TAN': 'Tanzania',
    'THA': 'Thailand',
    'TLS': 'Timor-Leste',
    'TOG': 'Togo',
    'TGA': 'Tonga',
    'TRI': 'Trinidad and Tobago',
    'TUN': 'Tunisia',
    'TUR': 'Türkiye',
    'TKM': 'Turkmenistan',
    'TCA': 'Turks and Caicos Islands',
    'UGA': 'Uganda',
    'UKR': 'Ukraine',
    'UAE': 'United Arab Emirates',
    'URU': 'Uruguay',
    'VIR': 'US Virgin Islands',
    'USA': 'USA',
    'UZB': 'Uzbekistan',
    'VAN': 'Vanuatu',
    'VEN': 'Venezuela',
    'VIE': 'Vietnam',
    'WAL': 'Wales',
    'YEM': 'Yemen',
    'ZAM': 'Zambia',
    'ZIM': 'Zimbabwe'
}